### PR TITLE
Upgrade to Node 16

### PR DESCRIPTION
**Pull request by jonbrooks**
Fixes https://github.com/deepakputhraya/action-pr-title/issues/24

### CODE REVIEW

**Review by dmathiazo — APPROVED** [review]

**Comment by mikelax** [comment]
Can we get this PR merged as this action needs to be updated past node v12. 
In fact, you should consider going right to node 20 as that was just [released in September](https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/).

**Comment by kishaningithub** [comment]
Linking the node upgrade 20 PR here https://github.com/deepakputhraya/action-pr-title/pull/39

**Comment by deepakputhraya** [comment]
https://github.com/deepakputhraya/action-pr-title/pull/39

**Comment by kishaningithub** [comment]
@deepakputhraya Can you tag a new major release since upgrading a node version is a breaking change?

**Comment by mikelax** [comment]
> @deepakputhraya Can you tag a new major release since upgrading a node version is a breaking change?

I don't think that we need a new release version cut as while the nodejs version was updated from 12 -> 20, the interface (params, etc) to the action hasn't changed. So there will be no real difference in using the action.

**Comment by kishaningithub** [comment]
Self hosted runners running on old machines like Amazon Linux 2 will definitely get affected as node 20 does not run during to its reliance on newer GLIBC version.

Also upgrading major version for node version bump is a standard practice, examples below

- https://github.com/actions/checkout/releases/tag/v4.0.0
- https://github.com/actions/setup-go/releases/tag/v5.0.0

**Pull request closed without merging**
