### PR TITLE
Upgrade to use latest NodeJs v20 and latest Github actions

### PR DESCRIPTION
**Pull request by franklychilled**

### CODE REVIEW

**Comment by antonindrawan** [comment]
Plus one! @deepakputhraya : Can this be merged?

**Comment by franklychilled** [comment]
> Plus one! @deepakputhraya : Can this be merged?

You can use our repo https://github.com/iress/action-pr-title if you wish. We are going to maintain it for our company.

**Comment by pdeschen** [comment]
> > Plus one! @deepakputhraya : Can this be merged?
> 
> @antonindrawan You can use our repo https://github.com/iress/action-pr-title if you wish. We are going to maintain it for our company.

Nice but it would be beneficial if you are to take over to update the readme, and get to marketplace...

**Comment by franklychilled** [comment]
> > > Plus one! @deepakputhraya : Can this be merged?
> > 
> > 
> > @antonindrawan You can use our repo [iress/action-pr-title](https://github.com/iress/action-pr-title) if you wish. We are going to maintain it for our company.
> 
> @franklychilled Nice but it would be beneficial if you are to take over to update the readme, and get to marketplace...

I've updated our readme file and I will like to see what is necessary to list our to the Github marketplace

**Pull request closed without merging**
